### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Briana83** [enigma-dev/lgmplugin#31]
Operating System: Linux
Version: 3.2.0-77-generic
Architecture: i386

Java Vendor: Oracle Corporation
Version: 1.7.0_75

Available processors (cores): 2
Free memory (bytes): 28153336
Maximum memory (bytes): 646971392
Total memory available to JVM (bytes): 57671680

File system root: /
Total space (bytes): 306667200512
Free space (bytes): 288965296128
Usable space (bytes): 273387442176

Stack trace:

org.enigma.SettingsHandler$YamlException: /home/briana/settings.ey: File not found
	at org.enigma.SettingsHandler.parseOptions(SettingsHandler.java:118)
	at org.enigma.SettingsHandler.<clinit>(SettingsHandler.java:94)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:70)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:394)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
	at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:1049)
	at org.lateralgm.main.LGM.addPluginResource(LGM.java:1010)
	at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:349)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:133)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:773)
	at org.lateralgm.main.LGM.main(LGM.java:2641)

java.lang.ExceptionInInitializerError
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:70)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:394)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
	at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:1049)
	at org.lateralgm.main.LGM.addPluginResource(LGM.java:1010)
	at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:349)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:133)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:773)
	at org.lateralgm.main.LGM.main(LGM.java:2641)
Caused by: java.lang.NullPointerException
	at org.enigma.SettingsHandler.parseExtensions(SettingsHandler.java:194)
	at org.enigma.SettingsHandler.<clinit>(SettingsHandler.java:100)
	... 15 more

**Comment by RobertBColton** [comment]
@Briana83 Hello, please see the solution in #37 and let me know if that fixes it.

**Comment by RobertBColton** [comment]
Closing issue as a duplicate and no response for almost a year.

**Comment by Briana83** [comment]
Sorry started GM itself more.

Briana Lyn Delaney - smarter than your average amoeba!

**Comment by RobertBColton** [comment]
@Briana83 did that fix the issue?
