### ISSUE TITLE
Invalid memory access

### ISSUE THREAD

**Issue by dagmatritsa2015** [enigma-dev/lgmplugin#33]
Operating System: Windows XP
Version: 5.1
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_45

Available processors (cores): 2
Free memory (bytes): 214768448
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: C:\
Total space (bytes): 21583101952
Free space (bytes): 3134107648
Usable space (bytes): 3134107648

File system root: E:\
Total space (bytes): 30005788672
Free space (bytes): 20792651776
Usable space (bytes): 20792651776

Stack trace:

java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:470)
	at com.sun.jna.Function.invokeString(Function.java:651)
	at com.sun.jna.Function.invoke(Function.java:395)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy0.libInit(Unknown Source)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:191)

**Comment by dagmatritsa2015** [comment]
solved. http://enigma-dev.org/forums/index.php?topic=2118.0;wap2
