### ISSUE TITLE
Cant open ENIGMA because of LGM

### ISSUE THREAD

**Issue by ismetagaoglu** [enigma-dev/lgmplugin#34]
I installed ENIGMA just now. When I open it loads until "Loading Plugins" text comes out. Then it crashes and gives me error:

(Sorry for english :( )

Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.7.0_80

Available processors (cores): 1
Free memory (bytes): 219021184
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: C:\
Total space (bytes): 54663311360
Free space (bytes): 2786983936
Usable space (bytes): 2786983936

File system root: D:\
Total space (bytes): 195288887296
Free space (bytes): 14606168064
Usable space (bytes): 14606168064

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.ExceptionInInitializerError
    at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:70)
    at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
    at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:394)
    at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
    at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:1010)
    at org.lateralgm.main.LGM.addPluginResource(LGM.java:971)
    at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:349)
    at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:133)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.lateralgm.main.LGM.loadPlugins(LGM.java:737)
    at org.lateralgm.main.LGM.main(LGM.java:2602)
Caused by: java.lang.IndexOutOfBoundsException: id
    at org.enigma.file.YamlParser$YamlNode.getM(YamlParser.java:61)
    at org.enigma.file.YamlParser$YamlNode.getMC(YamlParser.java:68)
    at org.enigma.SettingsHandler.parseExtensions(SettingsHandler.java:202)
    at org.enigma.SettingsHandler.<clinit>(SettingsHandler.java:100)
    ... 15 more

**Comment by RobertBColton** [comment]
Ok so what happened was that the original exception starts in the YAML parser running over the extensions About.ey files. It looks like "id" was missing from some extension in ENIGMA at the type, which is not the case now because in https://github.com/enigma-dev/lgmplugin/commit/ccc750ac54745d05599299549c13a29d91b659d4 I changed it to use "name" which is the appropriate human readable field for the GUI as it is in major systems for collisions, audio, and graphics.
https://github.com/enigma-dev/lgmplugin/blob/796232a0b961db2fdc979f5a64ccdd6f2acbe95c/org/enigma/SettingsHandler.java#L202

**Comment by RobertBColton** [comment]
@ismetagaoglu Could you possibly uppload the contents of the Extensions folder for me first as well? I want to take a look at the extensions and see which one of them is goofed up. I can't seem to find anything by searching commit history on master.

**Comment by RobertBColton** [comment]
Closing as this issue has gotten kind of stale, we've fixed Travis CI now so it can tell us when an extension screws up:
https://github.com/enigma-dev/enigma-dev/pull/1077

This problem hopefully shouldn't happen again in the future, but please open a new ticket if you discover any new issues.
