### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Woffelson** [enigma-dev/lgmplugin#37]
I'm surprised that I've even managed so far to install this but I get this error at the startup. I hope someone could help with that.

Operating System: Linux
Version: 3.13.0-61-generic
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_79

Available processors (cores): 2
Free memory (bytes): 68079824
Maximum memory (bytes): 1392508928
Total memory available to JVM (bytes): 120061952

File system root: /
Total space (bytes): 236154146816
Free space (bytes): 26352640000
Usable space (bytes): 14333075456

Stack trace:

org.enigma.SettingsHandler$YamlException: /home/arello/settings.ey: File not found
	at org.enigma.SettingsHandler.parseOptions(SettingsHandler.java:118)
	at org.enigma.SettingsHandler.<clinit>(SettingsHandler.java:94)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:70)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:394)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
	at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:1049)
	at org.lateralgm.main.LGM.addPluginResource(LGM.java:1010)
	at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:349)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:133)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:773)
	at org.lateralgm.main.LGM.main(LGM.java:2641)

java.lang.ExceptionInInitializerError
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:70)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:394)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
	at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:1049)
	at org.lateralgm.main.LGM.addPluginResource(LGM.java:1010)
	at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:349)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:133)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:773)
	at org.lateralgm.main.LGM.main(LGM.java:2641)
Caused by: java.lang.NullPointerException
	at org.enigma.SettingsHandler.parseExtensions(SettingsHandler.java:194)
	at org.enigma.SettingsHandler.<clinit>(SettingsHandler.java:100)
	... 15 more

**Comment by JoshDreamland** [comment]
From what directory are you running LGM? Looks like `~`. This just means it can't find the EY configuration files (in this case `settings.ey`) in your directory. Run it from LGM's directory (you can do this in a subshell to avoid polluting your current directory, eg, `(cd ENIGMA && java -jar lateralgm.jar)`.

**Comment by Woffelson** [comment]
lateralgm.jar was installed into the home folder. I moved it into the enigma-dev folder, opened it there and now it works. Thanks!
