### ISSUE TITLE
Copying and pasteing actions throws error

### ISSUE THREAD

**Issue by Shadowblitz16** [enigma-dev/lgmplugin#40]
when I put a "execute a peice of code" in the create event I can't copy it to the step event

Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_71

Available processors (cores): 4
Free memory (bytes): 174100536
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259588096

File system root: C:\
Total space (bytes): 618240405504
Free space (bytes): 481203814400
Usable space (bytes): 481203814400

File system root: D:\
Total space (bytes): 367002341376
Free space (bytes): 161262776320
Usable space (bytes): 161262776320

File system root: E:\
Total space (bytes): 3320903680
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.ClassCastException: java.util.Collections$EmptyList cannot be cast to java.util.ArrayList
	at org.lateralgm.components.ActionList.ActionsCopy(ActionList.java:1317)
	at org.lateralgm.components.ActionList.ActionsCut(ActionList.java:1310)
	at org.lateralgm.components.ActionList.actionPerformed(ActionList.java:1429)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by RobertBColton** [comment]
Thank you for reporting this, this is something I missed in the latest release as well. It however is a LateralGM issue and not an lgmplugin issue so I have moved this ticket over there instead.

**Comment by RobertBColton** [comment]
Posting on the original issue here too. It has finally been fixed in LateralGM v1.8.44 and you can download a release containing the fix below.
https://github.com/IsmAvatar/LateralGM/releases/tag/v1.8.44
