### ISSUE TITLE
Program Files (x86) install/MinGW32 does not like parens in the environment path

### ISSUE THREAD

**Issue by Biep** [enigma-dev/lgmplugin#41]
Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_60

Available processors (cores): 2
Free memory (bytes): 196528640
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 480673525760
Free space (bytes): 287970488320
Usable space (bytes): 287970488320

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (win32-x86-64/compileEGMf.dll) not found in resource path ([file:/C:/Program%20Files%20(x86)/Prog/Spel/2D/ENIGMA/enigma-dev/plugins/enigma.jar])
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
    at com.sun.jna.Library$Handler.<init>(Library.java:147)
    at com.sun.jna.Native.loadLibrary(Native.java:412)
    at com.sun.jna.Native.loadLibrary(Native.java:391)
    at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:247)
    at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:240)
    at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:178)

When double-clicking lateralgm.jar in enigma-dev, I get this:
Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_60

Available processors (cores): 2
Free memory (bytes): 63668920
Maximum memory (bytes): 954728448
Total memory available to JVM (bytes): 84934656

File system root: C:\
Total space (bytes): 480673525760
Free space (bytes): 287960076288
Usable space (bytes): 287960076288

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
org.lateralgm.file.GmFormatException: java.io.IOException: Cannot run program "mingw32-make.exe" (in directory "C:\Program Files (x86)\Prog\Spel\2D\ENIGMA\enigma-dev"): CreateProcess error=2, Het systeem kan het opgegeven bestand niet vinden
    at java.lang.ProcessBuilder.start(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at org.enigma.EnigmaRunner.make(EnigmaRunner.java:308)
    at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:173)

There is a mingw32-make.exe in 'mingw32\bin' in the main ENIGMA folder, but no mingw stuff in enigma-dev.
I am a n00b when it comes to C.

**Comment by RobertBColton** [comment]
ENIGMA currently does not support spaces in its installation path. Please move it to C:/Users/MyUserName/Desktop/ENIGMA or to C:/ENIGMA or any other path that does not contain spaces. If this does not work please let us know.
