### ISSUE TITLE
And this happened..

### ISSUE THREAD

**Issue by Amaroo** [enigma-dev/lgmplugin#52]
`Operating System: Linux
Version: 3.19.0-69-generic
Architecture: i386

Java Vendor: Oracle Corporation
Version: 1.8.0_45-internal

Available processors (cores): 1
Free memory (bytes): 17642216
Maximum memory (bytes): 316276736
Total memory available to JVM (bytes): 35893248

File system root: /
Total space (bytes): 156081704960
Free space (bytes): 129096126464
Usable space (bytes): 121143988224

Stack trace:

java.lang.ExceptionInInitializerError
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:70)
	at org.enigma.backend.EnigmaSettings.<init>(EnigmaSettings.java:59)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:394)
	at org.enigma.EnigmaRunner$EnigmaSettingsPluginResource.getInstance(EnigmaRunner.java:1)
	at org.lateralgm.main.LGM$SingletonPluginResource.getResourceHolder(LGM.java:1049)
	at org.lateralgm.main.LGM.addPluginResource(LGM.java:1010)
	at org.enigma.EnigmaRunner.addResourceHook(EnigmaRunner.java:349)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:133)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:773)
	at org.lateralgm.main.LGM.main(LGM.java:2641)
Caused by: java.lang.IndexOutOfBoundsException: id
	at org.enigma.file.YamlParser$YamlNode.getM(YamlParser.java:61)
	at org.enigma.file.YamlParser$YamlNode.getMC(YamlParser.java:68)
	at org.enigma.SettingsHandler.parseExtensions(SettingsHandler.java:202)
	at org.enigma.SettingsHandler.<clinit>(SettingsHandler.java:100)
	... 15 more
`

This is pretty much after I pulled.  Worked before.  Also how to get enigma to C++ compile since the error comes up that it fails?

**Comment by RobertBColton** [comment]
There were some changes made to the About.ey files which require the new plugin. Please see the announcement here:
http://enigma-dev.org/forums/index.php?topic=2718.0

These were further corrected by the Travis CI fixes:
https://github.com/enigma-dev/enigma-dev/pull/1077

Give those a test if you are still having problems, and open a new ticket for any new issues please.
