### ISSUE TITLE
No idea what the problem is...

### ISSUE THREAD

**Issue by Spaceman89** [enigma-dev/lgmplugin#56]
I just got the software, and it gave me error about game maker... I thought this is supposed to be separate dev tool from what I learned at Google.

Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_151

Available processors (cores): 4
Free memory (bytes): 196093400
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 89023049728
Free space (bytes): 41438621696
Usable space (bytes): 41438621696

File system root: D:\
Total space (bytes): 455081979904
Free space (bytes): 261171224576
Usable space (bytes): 261171224576

File system root: E:\
Total space (bytes): 455992143872
Free space (bytes): 122011508736
Usable space (bytes): 122011508736

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: G:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: H:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: J:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\Program Files\Gmaker8\Blacksmith\RTS\RTS.gmk
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.lateralgm.components.GmMenuBar.updateRecentFiles(GmMenuBar.java:86)
	at org.lateralgm.components.GmMenuBar.<init>(GmMenuBar.java:139)
	at org.lateralgm.main.LGM.main(LGM.java:2288)

java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\Program Files\Gmaker8\Blacksmith\Paint\Paint.gmk
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.lateralgm.components.GmMenuBar.updateRecentFiles(GmMenuBar.java:86)
	at org.lateralgm.components.GmMenuBar.<init>(GmMenuBar.java:139)
	at org.lateralgm.main.LGM.main(LGM.java:2288)

java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(Unknown Source)
	at java.awt.SplashScreen.update(Unknown Source)
	at org.lateralgm.main.LGM$SplashProgress.update(LGM.java:2796)
	at org.lateralgm.main.LGM$SplashProgress.progress(LGM.java:2789)
	at org.lateralgm.main.LGM.main(LGM.java:2290)

**Comment by JoshDreamland** [comment]
Hi there,

I'm not sure what gives you the impression that these errors relate to Game Maker; as far as I can tell, these are non-fatal errors involving parsing through your recently-opened files (and also displaying the main splash screen). While it is strange that you are getting these errors, they should not impede your ability to use this software, correct?

The only mentions of Game Maker seem to be the names of files you opened previously.

**Comment by Spaceman89** [comment]
Well, I tryed to use the enigma.exe(or whatever it was called) - no progress. I just jumped straight to c++ codeblox. Thanks for the help anyway.

**Comment by JoshDreamland** [comment]
This project is rooted in Game Maker, if that is what you're asking. LateralGM displayed your Game Maker files because it is capable of opening them. That compatibility is one of the selling points of this software. That said, the projects are quite different, and there is no code or binary dependency between them.

Regardless, good luck with your search for a gamedev framework.
