### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Valkia-INNOS** [enigma-dev/lgmplugin#68]
After installation to try it i get this error

LateralGM Version: 1.8.40

Operating System: Linux
Version: 4.15.0-43-generic
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 11.0.2

Available processors (cores): 12
Free memory (bytes): 240561664
Maximum memory (bytes): 4200595456
Total memory available to JVM (bytes): 264241152

File system root: /
Total space (bytes): 491180957696
Free space (bytes): 442173714432
Usable space (bytes): 417151651840

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (linux-x86-64/libcompileEGMf.so) not found in resource path ([file:/home/valkia-innos/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:248)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:241)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:179)

how can i solve this? 
ps: running on Ubuntu 18.04

**Comment by JoshDreamland** [comment]
What directory are you running LGM from? It needs to be run from the directory that contains LGM and `libcompileEGMf.so`.

**Comment by RobertBColton** [comment]
Automatically closing as sufficient time has passed without any feedback. If you need additional assistance, please feel free to file a new issue, ask on the forums, or join the Discord server.
