### ISSUE TITLE
got this error while debugging but game runs fine

### ISSUE THREAD

**Issue by Hughtech** [enigma-dev/lgmplugin#84]
while running my new project, game run fine except for the background sprite disappearing 2 minutes into the game. I tried to debug the game and this is the error i got........

LateralGM Version: 1.8.183
Working Directory: C:\msys32\home\enigma-dev\lateralgm.jar

Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_261

Current Thread: AWT-EventQueue-0
Available processors (cores): 2
Free memory (bytes): 4517520
Maximum memory (bytes): 259522560
Total memory available to JVM (bytes): 16252928

File system root: C:\
Total space (bytes): 159934050304
Free space (bytes): 113895444480
Usable space (bytes): 113895444480

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

javax.swing.text.StateInvariantError: GlyphView: Stale view: javax.swing.text.BadLocationException: Length must be positive
	at javax.swing.text.GlyphView.getText(Unknown Source)
	at javax.swing.text.GlyphView.getBreakSpot(Unknown Source)
	at javax.swing.text.GlyphView.getBreakWeight(Unknown Source)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at javax.swing.text.BoxView.layout(Unknown Source)
	at javax.swing.text.BoxView.setSize(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI$RootView.paint(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.paint(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

javax.swing.text.StateInvariantError: GlyphView: Stale view: javax.swing.text.BadLocationException: Length must be positive
	at javax.swing.text.GlyphView.getText(Unknown Source)
	at javax.swing.text.GlyphView.getBreakSpot(Unknown Source)
	at javax.swing.text.GlyphView.getBreakWeight(Unknown Source)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI$RootView.getMinimumSpan(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.getMinimumSize(Unknown Source)
	at javax.swing.JEditorPane.getScrollableTracksViewportWidth(Unknown Source)
	at javax.swing.JEditorPane.getPreferredSize(Unknown Source)
	at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)

**Comment by Hughtech** [comment]
found the problem. a memory leak was being done in part of the code i had wrote. Suffice to say i had to re-write that faulty code.

**Comment by RobertBColton** [comment]
Hugar this is actually still a bug though, the output window has concurrency issues in the plugin because it's mutating Swing components from a thread which isn't the EDT.
