### ISSUE TITLE
Changing anything in Build > Settings causes an error

### ISSUE THREAD

**Issue by TheSyrethClan** [enigma-dev/lgmplugin#86]
LateralGM Version: 1.8.227
Working Directory: C:\enigma-dev\lateralgm.jar

Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_161

Current Thread: AWT-EventQueue-0
Available processors (cores): 8
Free memory (bytes): 105041464
Maximum memory (bytes): 1886912512
Total memory available to JVM (bytes): 128974848

File system root: C:\
Total space (bytes): 998817951744
Free space (bytes): 220910518272
Usable space (bytes): 220910518272

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.NoSuchFieldError: changed
	at org.enigma.frames.EnigmaSettingsHandler.setResourceChanged(EnigmaSettingsHandler.java:1053)
	at org.lateralgm.subframes.ResourceFrame.setResourceChanged(ResourceFrame.java:214)
	at org.lateralgm.subframes.ResourceFrame.doDefaultSaveAction(ResourceFrame.java:228)
	at org.lateralgm.subframes.ResourceFrame.actionPerformed(ResourceFrame.java:238)
	at org.lateralgm.subframes.GameSettingFrame.actionPerformed(GameSettingFrame.java:1002)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

---

So far I have tried changing the java versions, and re-installing from scratch on my other machine. Same error.

**Comment by RobertBColton** [comment]
This is fixed by #87 which I've now merged.

You can run `./install.sh` to update the LGM-ENIGMA plugin, or manually download plugin 1.8.227 and copy it to `enigma-dev/plugins/enigma.jar` to update it.
