### ISSUE TITLE
error at start up

### ISSUE THREAD

**Issue by kodiboz** [enigma-dev/lgmplugin#91]
I tried installin using the script at https://enigma-dev.org/docs/Wiki/Install:Linux

it didnt download the enigma-dev from github, so I tried manually downloading and then and running.  I noticed that there was no way to run/test/compile a game created.  it didnt download the enigma.jar in the plugings, so I manually downloaded and put that file in the plugins folder...I feel like I have kinda frankenstein'd this together... any advice would be greatly appreciated.

I REALLY like what you guys are doing. I loved gamemaker and hope to create games using my preferred OS ( Linux), but I just cant seem to get it to work.

Thank you for all you and your team do!

KodiBoz2016

______________
LateralGM Version: 1.8.234
Working Directory: /home/mint/Downloads/enigma-dev/lateralgm.jar

Operating System: Linux
Version: 5.4.0-113-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Private Build
Version: 11.0.15

Current Thread: AWT-EventQueue-0
Available processors (cores): 4
Free memory (bytes): 241405184
Maximum memory (bytes): 4164943872
Total memory available to JVM (bytes): 264241152

File system root: /
Total space (bytes): 234154766336
Free space (bytes): 60995076096
Usable space (bytes): 49029304320

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf':
libcompileEGMf.so: cannot open shared object file: No such file or directory
libcompileEGMf.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libcompileEGMf.so) not found in resource path ([file:/home/mint/Downloads/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.loadLibrary(Native.java:646)
	at com.sun.jna.Native.loadLibrary(Native.java:630)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:251)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:244)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:176)
	Suppressed: java.lang.UnsatisfiedLinkError: libcompileEGMf.so: cannot open shared object file: No such file or directory
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: libcompileEGMf.so: cannot open shared object file: No such file or directory
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 7 more
	Suppressed: java.io.IOException: Native library (linux-x86-64/libcompileEGMf.so) not found in resource path ([file:/home/mint/Downloads/enigma-dev/plugins/enigma.jar])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 7 more

**Comment by fundies** [comment]
Can you show the output of ```make``` from the enigma directory?

**Comment by 0xzerk** [comment]
> Can you show the output of `make` from the enigma directory?

It spits out this
```
make -C shared/protos/
make[1]: Entering directory '/home/ms/enigma-dev/shared/protos'
protoc -I. --grpc_out=.eobjs --plugin=protoc-gen-grpc= server.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs treenode.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Timeline.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Sprite.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Sound.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Shader.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Settings.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs server.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Script.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Room.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs project.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Path.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs options.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Object.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Include.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs game.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs GameInformation.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Font.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs EventDescriptor.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs compiler.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Background.proto
make[1]: protoc: No such file or directory
protoc -I. --cpp_out=.eobjs Action.proto
make[1]: protoc: No such file or directory
make[1]: *** No rule to make target '.eobjs/Action.pb.cc', needed by '.eobjs/Action.pb.o'.  Stop.
make[1]: Leaving directory '/home/ms/enigma-dev/shared/protos'
make: *** [Makefile:42: libProtocols] Error 2
```
