### ISSUE TITLE
I only sometimes get this error when setting the window borderless in the settings

### ISSUE THREAD

**Issue by linux-leo** [enigma-dev/lgmplugin#92]
LateralGM Version: 1.8.234
Working Directory: C:\STIGMA\stigma-dev-Windows-x86_64\LateralGM-Windows-x86_64.exe

Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: ojdkbuild
Version: 1.8.0_322

Current Thread: AWT-EventQueue-0
Available processors (cores): 16
Free memory (bytes): 123263192
Maximum memory (bytes): 3661627392
Total memory available to JVM (bytes): 150994944

File system root: C:\
Total space (bytes): 686391455744
Free space (bytes): 560507428864
Usable space (bytes): 560507428864

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.NullPointerException
	at javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:563)
	at javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:477)
	at javax.swing.text.FlowView.layout(FlowView.java:201)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:348)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI$RootView.paint(BasicTextUI.java:1433)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:737)
	at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:881)
	at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1092)
	at javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1605)
	at javax.swing.JViewport.windowBlitPaint(JViewport.java:1558)
	at javax.swing.JViewport.setViewPosition(JViewport.java:1100)
	at javax.swing.JViewport.scrollRectToVisible(JViewport.java:436)
	at javax.swing.JComponent.scrollRectToVisible(JComponent.java:3111)
	at javax.swing.text.DefaultCaret.adjustVisibility(DefaultCaret.java:285)
	at javax.swing.text.DefaultCaret.repaintNewCaret(DefaultCaret.java:1313)
	at javax.swing.text.DefaultCaret$1.run(DefaultCaret.java:1287)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.NullPointerException
	at javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:563)
	at javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:477)
	at javax.swing.text.FlowView.layout(FlowView.java:201)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:348)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI$RootView.paint(BasicTextUI.java:1433)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:737)
	at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:881)
	at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1092)
	at javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1605)
	at javax.swing.JViewport.windowBlitPaint(JViewport.java:1558)
	at javax.swing.JViewport.setViewPosition(JViewport.java:1100)
	at javax.swing.JViewport.scrollRectToVisible(JViewport.java:436)
	at javax.swing.JComponent.scrollRectToVisible(JComponent.java:3111)
	at javax.swing.text.DefaultCaret.adjustVisibility(DefaultCaret.java:285)
	at javax.swing.text.DefaultCaret.repaintNewCaret(DefaultCaret.java:1313)
	at javax.swing.text.DefaultCaret$1.run(DefaultCaret.java:1287)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.NullPointerException
	at javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:563)
	at javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:477)
	at javax.swing.text.FlowView.layout(FlowView.java:201)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:348)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI$RootView.paint(BasicTextUI.java:1433)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:737)
	at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:881)
	at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1092)
	at javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1605)
	at javax.swing.JViewport.windowBlitPaint(JViewport.java:1558)
	at javax.swing.JViewport.setViewPosition(JViewport.java:1100)
	at javax.swing.JViewport.scrollRectToVisible(JViewport.java:436)
	at javax.swing.JComponent.scrollRectToVisible(JComponent.java:3111)
	at javax.swing.text.DefaultCaret.adjustVisibility(DefaultCaret.java:285)
	at javax.swing.text.DefaultCaret.repaintNewCaret(DefaultCaret.java:1313)
	at javax.swing.text.DefaultCaret$1.run(DefaultCaret.java:1287)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.NullPointerException

java.lang.NullPointerException

java.lang.NullPointerException

java.lang.NullPointerException

**Comment by hpgDesigns** [comment]
hi.............
seems like this version of OpenJDK is too old. remove and try installing OpenJDK 11 or the newest version.

those errors are related to Java.

**Comment by linux-leo** [comment]
Then im closing this for now.
